blog/urls.py
from django.urls import path

from . import views
app_name = 'blog'
urlpatterns = [
    
    path('', views.blogs, name='blogs'),
    path('<int:blog_id>', views.details, name='details'),
    
]

portfolio_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    date = models.DateTimeField()
    body = models.TextField(blank=True)

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=40)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.
def blogs(request):
    count = Blog.objects.count()
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/blogs.html', {'blogs': blogs, 'blogs_count':count})


def details(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/details.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="{% static 'portfolio/logo1.png' %}">
    <title>Khaled's Blog</title>
</head>
<body>
    <nav id="topNav" class="navbar navbar-expand-md navbar-light bg-ligh">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'portfolio/logo1.png' %}" width="30" height="30" class="d-inline-block align-top"
                    alt="Nick's Logo">
                <span>Khaled Alabssi</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse text-center" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link disabled" style="text-decoration: line-through;" href="#">Resume</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://www.linkedin.com/in/khaled-alabssi/" target="_blank">LinkedIn </a>
                    </li>
                    
                    <li>
                        <a role="button" href="{% url 'home' %}" class="btn btn-primary">Portfolio</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <br>
    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" 
integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" 
integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
</body>
</html>

blog/templates/blog/blogs.html
{% extends 'blog/base.html' %}
{% block content %}


<br>

<h3>Khaled has written {{ blogs_count }} blog{{ blogs_count | pluralize }}</h3>
<br>
{% for blog in blogs %}
<a href="{% url 'blog:details' blog.id %}"><h2>{{ blog.title }}</h2></a>
<br>
<h5>{{blog.date | date:'M d Y' | upper}}</h5>
<br>
<p>{{ blog.body |striptags| truncatechars:150 }}</p>
<hr>
{% endfor %}
{% endblock %}

blog/templates/blog/details.html
{% extends 'blog/base.html' %}
{% block content %}


<br>
<h1>{{ blog.title }}</h1>
<br>
<h3>--{{ blog.date|date:'F jS y' }}--</h3>
<br>
{{ blog.body|safe }}

{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="icon" type="image/png" href="{% static 'portfolio/logo1.png' %}">
    <title>Khaled Alabssi</title>
</head>

<body>
    <nav id="topNav" class="navbar navbar-expand-md navbar-light bg-ligh">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'portfolio/logo1.png' %}" width="30" height="30" class="d-inline-block align-top"
                    alt="Nick's Logo">
                <span>Khaled Alabssi</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse text-center" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link disabled" style="text-decoration: line-through;" href="#">Resume</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://www.linkedin.com/in/khaled-alabssi/" target="_blank">LinkedIn </a>
                    </li>
                    
                    <li>
                        <a role="button" href="{% url 'blog:blogs' %}" class="btn btn-primary">Blog</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <br>
    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

</body>

</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% block content %}


<br>
{% load static %}
<div class="row justify-content-center my-3">
    <div class="col-5">
        <img src="{% static 'portfolio/me.JPG' %}" class="img-fluid">
    </div>
</div>

<div class="row justify-content-center mb-3">
    <div class="col-md-9 text-center">
        <h1 id="hometext" class="font-weight-bold">Hello from Munich 😊
        </h1>
    </div>
</div>

<h2 class="mt-5">Portfolio</h2>
<hr>
<div class="row">
    {% for project in projects %}
    <div class="col-lg-4 col-md-6">

        {% if project.url %}
        <a href="{{ project.url }}">
            <img src="{{ project.image.url }}" class="img-fluid mb-2">
        </a>
        {% else %}

        <img src="{{ project.image.url }}" class="img-fluid mb-2">
        {% endif %}
        <h3>{{ project.title }}</h3>
        <p>{{ project.description }}</p>

    </div>
    {% endfor %}
</div>



{% endblock %}